displayName=Rogue Chests FC
author=Underdog
description=Tools and information for the Rogue Chests friends chat
tags=rogue,chests,fc,friends chat
version=1.0
plugins=com.roguechestsfc.RogueChestsFcPlugin
build=standard